---
- name: Update package cache on Ubuntu
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update package cache on CentOS
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install Apache2 on Ubuntu
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install Apache2 on CentOS
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Create an Apache2 custom configuration file
  template:
    src: templates/apache.conf.j2
    dest: "{{ apache_conf_path }}"
    mode: '0644'
  notify: Restart Apache2
